name: Build & Push Docker to ECR
on:
  push:
    branches: [ develop, main ]
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [red-service, blue-service, green-service]
    steps:
      - uses: actions/checkout@v3
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: Login to ECR
        run: |
          aws ecr get-login-password --region ${{ secrets.AWS_REGION }}           | docker login --username AWS --password-stdin ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com
      - name: Build, Tag & Push
        run: |
          SERVICE=${{ matrix.service }}
          REPO=${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/$SERVICE
          TAG=${{ github.ref == 'refs/heads/main' && echo prod || echo develop }}
          docker build -t $REPO:$TAG services/$SERVICE
          docker push $REPO:$TAG
          if [ "$TAG" = "prod" ]; then
            docker tag $REPO:prod $REPO:latest
            docker push $REPO:latest
          fi
