name: QA Build & Test

on:
  push:
    branches: [ develop ]
    paths:
      - 'services/**'

jobs:
  test-and-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Determine changed service
        id: changed
        run: |
          SERVICE=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} \
            | grep '^services/' \
            | head -n1 \
            | cut -d/ -f2)
          echo "service=$SERVICE" >> $GITHUB_OUTPUT

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install & Test Changed Service
        run: |
          cd services/${{ steps.changed.outputs.service }}
          npm install
          npm test
