name: UAT Test & Deploy
on:
  workflow_dispatch:
  push:
    tags: [ 'v[0-9]+.*.*' ]
jobs:
  test-all-services:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: |
          for svc in services/*; do
            cd $svc && npm ci && npm test && cd ../..
          done
