name: UAT Test & Deploy

on:
  workflow_dispatch:
  push:
    tags:
      - 'v[0-9]+.*.*'

jobs:
  test-all-services:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install & Test All Services
        run: |
          for svc in services/*; do
            cd $svc
            npm install
            npm test
            cd ../..
          done
